### ISSUE TITLE
Add styling support to components

### ISSUE THREAD

**Issue by levivoelz** [specialdoom/proi-ui#21]
**Is your feature request related to a problem? Please describe.**
I'd like to add custom styles to components.

**Describe the solution you'd like**
Either add a `class` property and/or `style` property to components.

**Describe alternatives you've considered**
Add more options to components to make them more customizable.

**Additional context**
I like this library and want to use it.

**Comment by specialdoom** [comment]
@levivoelz Unfortunately there is no time for me right now to focus on proi-ui lib. After I finish my master degree this summer, I will focus on it. Feel free to make the changes and open a PR or whatever fits for you.

Thanks for your interest.

**Comment by specialdoom** [comment]
@levivoelz The development for the proi-ui is on again. First version has been released with some changes regarding the componentes. You can find all the details on the repo page.

Coming next:
- custom styles for components
- theming

**Comment by specialdoom** [comment]
Updated and will be included with version v2.0.0.
 
v2 is in alpha0
