### ISSUE TITLE
Documentation does not seem right

### ISSUE THREAD

**Issue by ArslanT57** [specialdoom/proi-ui#39]
The documentation tells you to import `@specialdoom/proi-ui/dist/proi-ui.css` to my project and apply styling but there is no dist folder in the @specialdoom/proi-ui/ folder and it raises an error. Instead the proi-ui.css is in src folder inside the proi-ui folder and not in dist folder.

**Comment by specialdoom** [comment]
It seems like it does not pack proi-ui.css. I'm looking into it.

**Comment by specialdoom** [comment]
Solved in v2.2.2

**Comment by ArslanT57** [comment]
Thank you for your support. :)
