### ISSUE TITLE
make the router of doc working

### ISSUE THREAD

**Issue by abbychau** [specialdoom/proi-ui#94]
for instance:

https://proi-ui.vercel.app can navigate to `https://proi-ui.vercel.app/story/lib-checkbox-stories-checkbox-story-svelte`

but actually it is a 404.

**Comment by specialdoom** [comment]
I'm aware of that. I'm in the process of changing the docs provider with `storybook`. So that should fix the issue. Thanks for reporting it anyway.

**Comment by abbychau** [comment]
i actually love the structure of histoire much more than storybook.

i can see https://svelte3.examples.histoire.dev/story/src-controlsvariant-story-svelte is working.

is there any unexpected problem?

**Comment by specialdoom** [comment]
i think there is something related to vercel config, i will check it now

**Comment by specialdoom** [comment]
@abbychau there is a PR with the `vercel.json` config, which was missing. can you try the preview deplyoment? it seems to be working now 😄

**Comment by abbychau** [comment]
yes the preview is working (y)
